name: Cleanup
on:
  schedule:
    - cron: "0 8 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  cleanup-containers:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 30 Days
        uses: dataaxiom/ghcr-cleanup-action@f092b48ba3b604b2a83690dc4b2bbb3392e1045f # v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: bazzite-custom-gnome,bazzite-custom-gnome-nvidia-open
          older-than: 30 days
          delete-orphaned-images: true
          keep-n-tagged: 0
          keep-n-untagged: 0

      - name: Delete Untagged Images
        uses: dataaxiom/ghcr-cleanup-action@f092b48ba3b604b2a83690dc4b2bbb3392e1045f # v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: bazzite-custom-gnome,bazzite-custom-gnome-nvidia-open
          delete-orphaned-images: true
          delete-untagged: true

  cleanup-workflows:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    steps:
      - name: Delete Workflows Older Than 30 Days
        uses: igorjs/gh-actions-clean-workflow@6163f58f7b631d9a938a52a1d0cca171c71b9b4c # TEMP FIX
        with:
          token: ${{ github.token }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          runs_older_than: 30
          runs_to_keep: 0
